CREATE TABLE people (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   dob DATE NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL
);